name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Bun
      run: curl -fsSL https://bun.sh/install | bash

    - name: Set up Bun
      run: |
        export BUN_INSTALL="/root/.bun"
        export PATH="$BUN_INSTALL/bin:$PATH"

    - name: Install dependencies
      run: bun install

    - name: Run the tests
      run: bun test

    - name: Build
      run: bun build
